<?php
//2017-12-06 18:58:35
return array (
  0 => 'conf/redis_key.ini',
  1 => 'conf/db_pool.ini',
  2 => 'conf/application.ini',
  3 => 'conf/redis_pool.ini',
  4 => 'composer.json',
  5 => 'public/index.php',
  6 => 'application/library/readme.txt',
  7 => 'application/library/Helper/Log.php',
  8 => 'application/library/Helper/Conf.php',
  9 => 'application/library/Comm/Redis.php',
  10 => 'application/library/Data/TestRedis.php',
  11 => 'application/library/Data/Test.php',
  12 => 'application/library/Api/Ucenter.php',
  13 => 'application/library/Model/Text1.php',
  14 => 'application/library/Model/Dict/UptCellDict.php',
  15 => 'application/library/Model/Dict/PoemDict.php',
  16 => 'application/controllers/Index.php',
  17 => 'application/controllers/Poem/Uptpoemdict.php',
  18 => 'application/controllers/Dict/Uptcelldict.php',
  19 => 'application/controllers/Dict/Uptcelldict62.php',
  20 => 'application/controllers/Dict/Uptcelldict65.php',
  21 => 'application/controllers/Error.php',
  22 => 'application/plugins/Sample.php',
  23 => 'application/Bootstrap.php',
  24 => 'composer.lock',
);
?>