<?php
//2017-12-06 18:50:59
return array (
  0 => 'check_nickname.php',
  1 => 'constants.php',
  2 => 'email_userinfo.php',
  3 => 'scripts/md5.php',
  4 => 'scripts/updatePassport.php',
  5 => 'scripts/syncUserBQB.php',
  6 => 'scripts/test.php',
  7 => 'scripts/HttpClient.class.php',
  8 => 'scripts/getuserinfo.php',
  9 => 'scripts/Passport_api.php',
  10 => 'scripts/passport.php',
  11 => 'scripts/mysqlUtil.class.php',
  12 => 'scripts/delKeys.php',
  13 => 'scripts/users.txt',
  14 => 'user/search/searchByNickname.php',
  15 => 'user/get_passportid_by_sgid.php',
  16 => 'user/mi/mi_config.php',
  17 => 'user/mi/mi_map.php',
  18 => 'user/mi/import_users.php',
  19 => 'email_userinfo_new.php',
  20 => 'config.php',
  21 => 'set_user_detail.php',
  22 => 'get_user_detail.php',
  23 => 'inc/user_function.php',
  24 => 'inc/constants.php',
  25 => 'inc/user_search.php',
  26 => 'inc/no_injection.php',
  27 => 'inc/user_main.php',
  28 => 'inc/functions.php',
  29 => 'inc/common.php',
  30 => 'skins/get_id_by_md5.php',
  31 => 'sgid_userinfo.php',
  32 => 'class/db_config.php',
  33 => 'class/MySQL.class.php',
  34 => 'class/MySQLUtil.class.php',
  35 => 'class/DB.php',
  36 => 'class/Redis.php',
  37 => 'openplatform/search.php',
  38 => 'openplatform/getEmailByUid.php',
  39 => 'pcid_userinfo.php',
  40 => 'update_user.php',
);
?>