<?php
//2017-12-06 18:54:16
return array (
  0 => 'macversion.php',
  1 => 'ini/unre.ini',
  2 => 'ini/rule.ini',
  3 => 'ini/chup.ini',
  4 => 'ini/mac_asso_dict.ini',
  5 => 'updateRate.sysd',
  6 => 'ABSConfig_20111019.ini',
  7 => 'readsysdF.php',
  8 => 'macassodict.php',
  9 => 'readIR.php',
  10 => 'readInfoKey2.php',
  11 => 'version.php',
  12 => 'updateRate.ime',
  13 => 'test.php',
  14 => 'updateRate',
  15 => 'addrservice.php',
  16 => 'fastversion.txt',
  17 => 'mc_test.php',
  18 => 'updateRate.ime1',
  19 => 'SuggConfig_enc_20100913.ini',
  20 => 'wbversion.php',
  21 => 'readBigWhiteDog.php',
  22 => 'readUrlGuide.php',
  23 => 'sogou_mac.xml',
  24 => 'sgupdate.php',
  25 => 'linux_version.php',
  26 => 'readInfoKey.php',
  27 => 'sogou.xml',
  28 => 'readPerf.php',
  29 => 'updateRate.ir',
  30 => 'install.gif.php',
  31 => 'yiliaoVersion.php',
  32 => 'sogouwubi.php',
);
?>