<?php
//2018-01-16 19:18:07
return array (
  0 => 'test/test.php',
  1 => 'android/interface_bq_detail.php',
  2 => 'android/skin_share.php',
  3 => 'android/ywz_zip_info.php',
  4 => 'iphone/interface_skin_ios.php',
  5 => 'iphone/interface_bq_detail.php',
  6 => 'iphone/skin_share.php',
  7 => 'dict/lbs.php',
  8 => 'dict/dict.php',
  9 => 'fenci/fenci.php',
  10 => 'skin/skin_ver_match.php',
  11 => 'skin/test.php',
  12 => 'skin/pc.php',
  13 => 'skin/config.php',
  14 => 'skin/fileadd_test.php',
  15 => 'skin/mobile.php',
  16 => 'skin/fileadd.php',
  17 => 'api/ios_10w_jingpin.php',
  18 => 'api/ios_10w_zuixin_small.php',
  19 => 'api/ios_10w_zuixin_large.php',
  20 => 'api/search_ios_reco.php',
  21 => 'appkey/mem.php',
  22 => 'js/pv.js',
  23 => 'js/share_skin.js',
  24 => 'expr/expr_pic.php',
  25 => 'expr/ywz_zip.php',
  26 => 'expr/expr.php',
  27 => 'expr/bqname.php',
  28 => 'expr/share_iphone.php',
  29 => 'expr/ywz_pic.php',
  30 => 'expr/config.php',
  31 => 'expr/express_zip_list.php',
  32 => 'interface_skin_all.php',
  33 => 'lib_utf8.php',
  34 => 'config.php',
  35 => 'config_mt.php',
  36 => 'core.nMemcache.php',
);
?>